### ISSUE TITLE
Plugin enable error

### ISSUE THREAD

**Issue by Atten007** [KeanBuyst/MCComputers#1]
Hey, I wanted to set up a Minecraft: Java Edition server with your plugin for my programming course next Wednesday. So I created a test server and uploaded the plugin there. But the plugin couldn't be enabled. Here's the log file:

Error occurred while enabling MCC v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/MCC-1.0-SNAPSHOT.jar
	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:180) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at mcc.MCC.onEnable(MCC.java:27) ~[MCC-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-199]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
I hope, this can be fixed very soon! 

Also, I've a question: Can the plugin run on 1.16.5?

Kind regards,
Atten 😊

**Comment by ststeppat** [comment]
The some Problem:

[07:41:15] [Server thread/ERROR]: Error occurred while enabling MCC v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/MCC-1.0-SNAPSHOT.jar
	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:180) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at mcc.MCC.onEnable(MCC.java:27) ~[MCC-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-199]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:41:15] [Server thread/INFO]: [MCC] Disabling MCC v1.0-SNAPSHOT

**Comment by Atten007** [comment]
> The some Problem:
> 
> [07:41:15] [Server thread/ERROR]: Error occurred while enabling MCC v1.0-SNAPSHOT (Is it up to date?) java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/MCC-1.0-SNAPSHOT.jar at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:180) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at mcc.MCC.onEnable(MCC.java:27) ~[MCC-1.0-SNAPSHOT.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-199] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-199] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-199] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-199] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-199] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-199] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-199] at java.lang.Thread.run(Thread.java:833) ~[?:?] [07:41:15] [Server thread/INFO]: [MCC] Disabling MCC v1.0-SNAPSHOT

However, it can be fixed by manually creating the config.yml file...

**Comment by KeanBuyst** [comment]
Sorry for the inconvenience. I have have fixed the error. If you find any other errors please tell me.

**Comment by Atten007** [comment]
> Sorry for the inconvenience. I have have fixed the error. If you find any other errors please tell me.

I found another error when the plugin is disabled, see #2

When are you uploading the bug fixes to SpigotMC.org?

**Comment by KeanBuyst** [comment]
> > Sorry for the inconvenience. I have have fixed the error. If you find any other errors please tell me.
> 
> I found another error when the plugin is disabled, see #2
> 
> When are you uploading the bug fixes to SpigotMC.org?

I have uploaded the new jar now.  Please remember to delete the MCC folder as well and destroy any currently placed computers and drones.
