### ISSUE TITLE
Plugin disable error

### ISSUE THREAD

**Issue by Atten007** [KeanBuyst/MCComputers#2]
Hey, I've found another error:

Error occurred while disabling MCC v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "this.block" is null
	at mcc.computer.objects.Computer.getLocation(Computer.java:73) ~[MCC-1.0-SNAPSHOT.jar:?]
	at mcc.storage.Storage.uploadComputer(Storage.java:42) ~[MCC-1.0-SNAPSHOT.jar:?]
	at mcc.MCC.onDisable(MCC.java:51) ~[MCC-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:808) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[paper-1.19.2.jar:git-Paper-199]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-199]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

If it can be fixed soon, I'll be very happy!

Kind regards,
Atten  😊

**Comment by KeanBuyst** [comment]
I have not been able to recreate this error. This may have been caused due to the enabling error. Please delete the MCC folder and download the updated jar that I posted. Hopefully this will fix your error.
