### ISSUE TITLE
Creating files and directories not working

### ISSUE THREAD

**Issue by allernotfound** [KeanBuyst/MCComputers#3]
When using `f create <filename>` and the Pastebin commands it doesn't seem to create a file. It also doesn't create a folder for the computer when you place one. When trying to run it with `python <filename>` it gives a Python error saying that the file does not exist. You can still create a folder for the computer yourself and add the python file and it runs fine, it just doesn't create files or folders itself.

Using version 1.20.4, paper

**Comment by allernotfound** [comment]
Edit: I get this error when I restart my server, I think it is related to a permission error.

```
[16:37:03 WARN]: java.io.IOException: Permission denied
[16:37:03 WARN]:        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
[16:37:03 WARN]:        at java.base/java.io.File.createNewFile(File.java:1043)
[16:37:03 WARN]:        at MCC-1.2-SNAPSHOT.jar//mcc.storage.Storage.uploadComputer(Storage.java:34)
[16:37:03 WARN]:        at MCC-1.2-SNAPSHOT.jar//mcc.MCC.onDisable(MCC.java:56)
[16:37:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290)
[16:37:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223)
[16:37:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147)
[16:37:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92)
[16:37:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528)
[16:37:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:570)
[16:37:03 WARN]:        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:974)
[16:37:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:822)
[16:37:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1265)
[16:37:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:37:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by KeanBuyst** [comment]
Sorry for the late response, haven't spent much time on this plugin in a while. Yes, it is most likely a permission problem. I don't get this error on my pc. Maybe try running the server with admin permissions. So for Linux `sudo run.sh` or whatever it is. Please let me know if this works and I will try my best to fix it if it doesn't.
